### ISSUE TITLE
After completing an ai task on a course lesson, the exercises tab remains empty

### ISSUE THREAD

**Issue by Enyeltov** [guillermoscript/lms-front#213] opened 2024-10-13 21:01 UTC
When i have finished a lesson and completed its task, the exercise tab on the course page doens't update this progress, and remains empty.

Task Completed:
![image](https://github.com/user-attachments/assets/39f540ca-3ab2-48a5-a0e7-2b19c4306b81)

Exercise tab not updated to reflect changes:
![image](https://github.com/user-attachments/assets/f2f15735-a94a-4835-9e2c-32a670813f50)

**Comment by guillermoscript** [comment] 2024-10-14 19:33
the exercises and the task are not the saem, the ai task is there to make the lesson as completed, but the exercise is just another set. I will close this as this is not a bug

**Closed by guillermoscript** 2024-10-14 19:33 UTC
